/** @type {import('tailwindcss').Config} */
export default {
  content: ['./index.html', './src/**/*.{js,ts,jsx,tsx}'],
  theme: {
    extend: {
      fontFamily: {
        sans: ['Poppins', 'Inter', '-apple-system', 'BlinkMacSystemFont', 'sans-serif'],
      },
      fontSize: {
        'headline-lg': ['24px', { lineHeight: '32px', letterSpacing: '-0.02em', fontWeight: '600' }],
        'headline-md': ['20px', { lineHeight: '28px', letterSpacing: '-0.01em', fontWeight: '600' }],
        'headline-lg-mobile': ['22px', { lineHeight: '28px', fontWeight: '600' }],
        'body-base': ['14px', { lineHeight: '20px', fontWeight: '400' }],
        'body-sm': ['12px', { lineHeight: '16px', fontWeight: '400' }],
        'label-md': ['14px', { lineHeight: '20px', fontWeight: '500' }],
        'label-sm': ['11px', { lineHeight: '12px', letterSpacing: '0.05em', fontWeight: '600' }],
        'display-lg': ['48px', { lineHeight: '56px', letterSpacing: '-0.02em', fontWeight: '700' }],
        'headline-lg-desktop': ['32px', { lineHeight: '40px', letterSpacing: '-0.01em', fontWeight: '600' }],
        'headline-md-desktop': ['24px', { lineHeight: '32px', fontWeight: '600' }],
        'body-lg': ['18px', { lineHeight: '28px', fontWeight: '400' }],
        'body-md': ['16px', { lineHeight: '24px', fontWeight: '400' }],
        'body-sm-desktop': ['14px', { lineHeight: '20px', fontWeight: '400' }],
        'label-md-desktop': ['14px', { lineHeight: '20px', fontWeight: '600', letterSpacing: '0.05em' }],
        'label-sm-desktop': ['12px', { lineHeight: '16px', fontWeight: '500' }],
      },
      colors: {
        surface: '#f5f9ff',
        'surface-dim': '#d6dce8',
        'surface-bright': '#f5f9ff',
        'surface-container-lowest': '#ffffff',
        'surface-container-low': '#eef4fc',
        'surface-container': '#e6eef8',
        'surface-container-high': '#dce5f0',
        'surface-container-highest': '#d0dae6',
        'on-surface': '#151b26',
        'on-surface-variant': '#424752',
        'inverse-surface': '#2c313b',
        'inverse-on-surface': '#eef2f9',
        outline: '#727886',
        'outline-variant': '#c2c7d4',
        'surface-tint': '#1c61b7',
        primary: '#1c61b7',
        'primary-hover': '#154d93',
        'on-primary': '#ffffff',
        'primary-container': '#6cbdee',
        'on-primary-container': '#0a305c',
        'inverse-primary': '#a3c9ff',
        'primary-fixed': '#d1e5ff',
        'primary-fixed-dim': '#a3c9ff',
        'on-primary-fixed': '#001b3d',
        'on-primary-fixed-variant': '#00458c',
        secondary: '#6cbdee',
        'on-secondary': '#00324d',
        'secondary-container': '#c6e7ff',
        'on-secondary-container': '#001e30',
        'secondary-fixed': '#c6e7ff',
        'secondary-fixed-dim': '#80ceff',
        'on-secondary-fixed': '#001e30',
        'on-secondary-fixed-variant': '#004b70',
        tertiary: '#f98433',
        'on-tertiary': '#ffffff',
        'tertiary-container': '#ffdcc2',
        'on-tertiary-container': '#331400',
        'tertiary-fixed': '#ffdcc2',
        'tertiary-fixed-dim': '#ffb784',
        'on-tertiary-fixed': '#331400',
        'on-tertiary-fixed-variant': '#7a3b00',
        error: '#ba1a1a',
        'on-error': '#ffffff',
        'error-container': '#ffdad6',
        'on-error-container': '#93000a',
        background: '#f5f9ff',
        'on-background': '#151b26',
        'surface-variant': '#dfe3ee',
        success: '#10B981',
        warning: '#F59E0B',
        info: '#6cbdee',
        // Desktop-specific overrides
        'desktop-surface': '#f5f8fc',
        'desktop-surface-container-low': '#eef2f8',
        'desktop-background': '#f5f8fc',
        'desktop-on-background': '#151b26',
      },
      borderRadius: {
        sm: '0.25rem',
        DEFAULT: '0.5rem',
        md: '0.75rem',
        lg: '1rem',
        xl: '1.5rem',
        '2xl': '1.75rem',
        full: '9999px',
        card: '16px',
        btn: '12px',
      },
      maxWidth: {
        content: '1280px',
      },
      boxShadow: {
        card: '0 1px 3px rgba(0,0,0,0.04)',
        'card-hover': '0 4px 12px rgba(0,0,0,0.06), 0 1px 2px rgba(0,0,0,0.04)',
        'card-elevated': '0 10px 25px -5px rgba(0,0,0,0.05), 0 4px 10px -2px rgba(0,0,0,0.03)',
        nav: '0 -1px 0 rgba(0,0,0,0.04)',
        header: '0 1px 0 rgba(0,0,0,0.04)',
        'glass-nav': '0 -1px 3px rgba(0,0,0,0.06)',
        clay: '6px 6px 12px rgba(28, 97, 183, 0.10), -4px -4px 10px rgba(255, 255, 255, 0.8)',
        'clay-sm': '4px 4px 8px rgba(28, 97, 183, 0.08), -3px -3px 6px rgba(255, 255, 255, 0.7)',
        'clay-inset': 'inset 3px 3px 6px rgba(28, 97, 183, 0.08), inset -3px -3px 6px rgba(255, 255, 255, 0.7)',
      },
      spacing: {
        safe: 'env(safe-area-inset-bottom, 0px)',
        18: '72px',
        'nav-top': '60px',
        'nav-bottom': '72px',
        gutter: '16px',
        'margin-mobile': '16px',
        'margin-desktop': '24px',
        'touch-target': '44px',
      },
      animation: {
        'slide-up': 'slideUp 0.3s ease-out',
        'fade-in': 'fadeIn 0.2s ease-out',
        'scale-in': 'scaleIn 0.2s ease-out',
        'dot-in': 'dotIn 200ms ease-out',
        'dot-out': 'dotOut 300ms ease-out forwards',
      },
      keyframes: {
        slideUp: {
          '0%': { transform: 'translateY(16px)', opacity: '0' },
          '100%': { transform: 'translateY(0)', opacity: '1' },
        },
        fadeIn: {
          '0%': { opacity: '0' },
          '100%': { opacity: '1' },
        },
        scaleIn: {
          '0%': { transform: 'scale(0.95)', opacity: '0' },
          '100%': { transform: 'scale(1)', opacity: '1' },
        },
        dotIn: {
          '0%': { opacity: '0', transform: 'scale(0)' },
          '100%': { opacity: '1', transform: 'scale(1)' },
        },
        dotOut: {
          '0%': { opacity: '1', transform: 'scale(1)' },
          '100%': { opacity: '0', transform: 'scale(0)' },
        },
      },
      backdropBlur: {
        nav: '8px',
      },
    },
  },
  plugins: [],
}
