/** @type {import('tailwindcss').Config} */
export default {
  content: ['./index.html', './src/**/*.{js,ts,jsx,tsx}'],
  theme: {
    extend: {
      fontFamily: {
        sans: ['Inter', '-apple-system', 'BlinkMacSystemFont', 'sans-serif'],
      },
      fontSize: {
        'headline-lg': ['24px', { lineHeight: '32px', letterSpacing: '-0.02em', fontWeight: '600' }],
        'headline-md': ['20px', { lineHeight: '28px', letterSpacing: '-0.01em', fontWeight: '600' }],
        'headline-lg-mobile': ['22px', { lineHeight: '28px', fontWeight: '600' }],
        'body-base': ['14px', { lineHeight: '20px', fontWeight: '400' }],
        'body-sm': ['12px', { lineHeight: '16px', fontWeight: '400' }],
        'label-md': ['14px', { lineHeight: '20px', fontWeight: '500' }],
        'label-sm': ['11px', { lineHeight: '12px', letterSpacing: '0.05em', fontWeight: '600' }],
        'display-lg': ['48px', { lineHeight: '56px', letterSpacing: '-0.02em', fontWeight: '700' }],
        'headline-lg-desktop': ['32px', { lineHeight: '40px', letterSpacing: '-0.01em', fontWeight: '600' }],
        'headline-md-desktop': ['24px', { lineHeight: '32px', fontWeight: '600' }],
        'body-lg': ['18px', { lineHeight: '28px', fontWeight: '400' }],
        'body-md': ['16px', { lineHeight: '24px', fontWeight: '400' }],
        'body-sm-desktop': ['14px', { lineHeight: '20px', fontWeight: '400' }],
        'label-md-desktop': ['14px', { lineHeight: '20px', fontWeight: '600', letterSpacing: '0.05em' }],
        'label-sm-desktop': ['12px', { lineHeight: '16px', fontWeight: '500' }],
      },
      colors: {
        surface: '#fcf8ff',
        'surface-dim': '#dcd8e5',
        'surface-bright': '#fcf8ff',
        'surface-container-lowest': '#ffffff',
        'surface-container-low': '#f5f2ff',
        'surface-container': '#f0ecf9',
        'surface-container-high': '#eae6f4',
        'surface-container-highest': '#e4e1ee',
        'on-surface': '#1b1b24',
        'on-surface-variant': '#464555',
        'inverse-surface': '#302f39',
        'inverse-on-surface': '#f3effc',
        outline: '#777587',
        'outline-variant': '#c7c4d8',
        'surface-tint': '#4d44e3',
        primary: '#3525cd',
        'primary-hover': '#2a1da8',
        'on-primary': '#ffffff',
        'primary-container': '#4f46e5',
        'on-primary-container': '#dad7ff',
        'inverse-primary': '#c3c0ff',
        'primary-fixed': '#e2dfff',
        'primary-fixed-dim': '#c3c0ff',
        'on-primary-fixed': '#0f0069',
        'on-primary-fixed-variant': '#3323cc',
        secondary: '#515f74',
        'on-secondary': '#ffffff',
        'secondary-container': '#d5e3fc',
        'on-secondary-container': '#57657a',
        'secondary-fixed': '#d5e3fc',
        'secondary-fixed-dim': '#b9c7df',
        'on-secondary-fixed': '#0d1c2e',
        'on-secondary-fixed-variant': '#3a485b',
        tertiary: '#7e3000',
        'on-tertiary': '#ffffff',
        'tertiary-container': '#a44100',
        'on-tertiary-container': '#ffd2be',
        'tertiary-fixed': '#ffdbcc',
        'tertiary-fixed-dim': '#ffb695',
        'on-tertiary-fixed': '#351000',
        'on-tertiary-fixed-variant': '#7b2f00',
        error: '#ba1a1a',
        'on-error': '#ffffff',
        'error-container': '#ffdad6',
        'on-error-container': '#93000a',
        background: '#fcf8ff',
        'on-background': '#1b1b24',
        'surface-variant': '#e4e1ee',
        success: '#10B981',
        warning: '#F59E0B',
        info: '#3B82F6',
        // Desktop-specific overrides
        'desktop-surface': '#f8f9fa',
        'desktop-surface-container-low': '#f3f4f5',
        'desktop-background': '#f8f9fa',
        'desktop-on-background': '#191c1d',
      },
      borderRadius: {
        sm: '0.25rem',
        DEFAULT: '0.5rem',
        md: '0.75rem',
        lg: '1rem',
        xl: '1.5rem',
        full: '9999px',
        card: '12px',
        btn: '10px',
      },
      maxWidth: {
        content: '1280px',
      },
      boxShadow: {
        card: '0 1px 3px rgba(0,0,0,0.04)',
        'card-hover': '0 4px 12px rgba(0,0,0,0.06), 0 1px 2px rgba(0,0,0,0.04)',
        'card-elevated': '0 10px 25px -5px rgba(0,0,0,0.05), 0 4px 10px -2px rgba(0,0,0,0.03)',
        nav: '0 -1px 0 rgba(0,0,0,0.04)',
        header: '0 1px 0 rgba(0,0,0,0.04)',
        'glass-nav': '0 -1px 3px rgba(0,0,0,0.06)',
      },
      spacing: {
        safe: 'env(safe-area-inset-bottom, 0px)',
        18: '72px',
        'nav-top': '60px',
        'nav-bottom': '72px',
        gutter: '16px',
        'margin-mobile': '16px',
        'margin-desktop': '24px',
        'touch-target': '44px',
      },
      animation: {
        'slide-up': 'slideUp 0.3s ease-out',
        'fade-in': 'fadeIn 0.2s ease-out',
        'scale-in': 'scaleIn 0.2s ease-out',
        'dot-in': 'dotIn 200ms ease-out',
        'dot-out': 'dotOut 300ms ease-out forwards',
      },
      keyframes: {
        slideUp: {
          '0%': { transform: 'translateY(16px)', opacity: '0' },
          '100%': { transform: 'translateY(0)', opacity: '1' },
        },
        fadeIn: {
          '0%': { opacity: '0' },
          '100%': { opacity: '1' },
        },
        scaleIn: {
          '0%': { transform: 'scale(0.95)', opacity: '0' },
          '100%': { transform: 'scale(1)', opacity: '1' },
        },
        dotIn: {
          '0%': { opacity: '0', transform: 'scale(0)' },
          '100%': { opacity: '1', transform: 'scale(1)' },
        },
        dotOut: {
          '0%': { opacity: '1', transform: 'scale(1)' },
          '100%': { opacity: '0', transform: 'scale(0)' },
        },
      },
      backdropBlur: {
        nav: '8px',
      },
    },
  },
  plugins: [],
}
